# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Services
  description: Services section
  icon: build
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  preheading: ""
  heading: ""
  sections:
    - title: ""
      icon: ""
      content: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  preheading: Our Services
  heading: "We provide a wide range of creative services "
  sections:
    - title: Web development
      icon: ti-desktop
      content: A digital agency isn't here to replace your internal team, we're here
        to partner.
    - title: Interface Design
      icon: ti-layers
      content: A digital agency isn't here to replace your internal team, we're here
        to partner.
    - title: Business Consulting
      icon: ti-bar-chart
      content: A digital agency isn't here to replace your internal team, we're here
        to partner.
    - icon: ti-vector
      title: Branding
      content: A digital agency isn't here to replace your internal team, we're here
        to partner.
    - title: App development
      icon: ti-android
      content: A digital agency isn't here to replace your internal team, we're here
        to partner.
    - title: Content creation
      icon: ti-pencil-alt
      content: A digital agency isn't here to replace your internal team, we're here
        to partner.

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
