# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Hero
  description: Hero block
  icon: pending
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  title: ""
  hero:
    title: ""
    background_image: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  title: Hero page
  hero:
    title: Hero
    background_image: /images/bg/home-2.jpg

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
