# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Numbers
  description: Numbers section
  icon: poll
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  sections:
    - title: ""
      text: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  sections:
    - title: Our Mission
      text: llum similique ducimus accusamus laudantium praesentium, impedit quaerat,
        itaque maxime sunt deleniti voluptas distinctio.
    - title: Vision
      text: llum similique ducimus accusamus laudantium praesentium, impedit quaerat,
        itaque maxime sunt deleniti voluptas distinctio.
    - title: Our Approach
      text: llum similique ducimus accusamus laudantium praesentium, impedit quaerat,
        itaque maxime sunt deleniti voluptas distinctio.

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
