# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: CTA
  description: CTA section
  icon: grade
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  background_image: ""
  preheading: ""
  heading: ""
  content: ""
  phone: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  background_image: /images/bg/home-3.jpg
  preheading: We create for you
  heading: Entrust Your Project to Our Best Team of Professionals
  content: "Have any project on mind? For immidiate support:"
  phone: +23 876 65 455

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
