# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Big Hero
  description: Main page Hero block
  icon: title
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  preheading: ""
  heading: ""
  background_image: ""
  link:
    text: ""
    url: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  preheading: Prepare for new future
  heading: Our work is <br>presentation of our <br>capabilities.
  background_image: /images/bg/home-1.jpg
  link:
    text: Get started
    url: "#"

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
