# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Counter
  description: Counter section
  icon: analytics
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  numbers:
    - number: 1730
      suffix: ""
      text: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  numbers:
    - suffix: +
      text: Projects Done
    - suffix: M
      text: Users Worldwide
    - suffix: Available Countries
    - suffix: Awards Won

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
