# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Intro
  description: Overview section
  icon: receipt
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  preheading: ""
  heading: ""
  sections:
    - title: ""
      icon: ""
      content: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  preheading: We are creative & expert people
  heading: We work with business & provide solution to client with their business
    problem
  sections:
    - title: Modern & Responsive design
      icon: ti-desktop
      content: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit, ducimus.
    - title: Awarded licensed company
      icon: ti-medall
      content: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit, ducimus.
    - title: Build your website Professionally
      icon: ti-layers
      content: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit, ducimus.

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
