# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Overview
  description: Overview section
  icon: theaters
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  preheading: ""
  heading: ""
  sections:
    - title: ""
      icon: ""
      text: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  preheading: We are creative
  heading: We provide best solution to client with their business problem
  sections:
    - title: Modern & Responsive design
      icon: ti-wand
      text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum,
        aspernatur.
    - title: Awarded licensed company
      icon: ti-medall
      text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum,
        aspernatur.

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
